### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by williamsexton** [williamsexton/Meat-Website-Fullstack-Project#2]
# User Auth
​
## Functionality
​
- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation
​
### Before Login
​
- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user
​
### After Login
​
- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in
​
​
## Style
​
- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production
​
## Seeds
- [x] Adequate and appropriate seeds

**Comment by ronilbhatia** [comment]
Hey Will, great job! I have a few comments related to styling, other than that just make sure to configure your store to not include the logger when in production and you should be good.

1. There should be some space between the nav bar and the actual form, like the actual website. Also looks like the actual website has a slight `box-shadow` around the sign up/sign in form, and a slight `border-radius` around the submit button of the form.
![Screen Shot 2020-05-01 at 11 36 50 AM](https://user-images.githubusercontent.com/32026924/80846228-6902e300-8bc0-11ea-81ee-4998b8e90001.png)

2. Would be nice if the 'Create Your Account' link had a different color than the 'Don't have an account?' test similar to the actual website, and that color changes when you hover on it.
3. When errors render they are right up against the bottom of the form, add some padding to the bottom of them so there's more room for them to breathe.
![Screen Shot 2020-05-01 at 11 36 52 AM](https://user-images.githubusercontent.com/32026924/80846229-6a341000-8bc0-11ea-99c2-5e5cb06fac48.png)
![Screen Shot 2020-05-01 at 3 08 19 PM](https://user-images.githubusercontent.com/32026924/80846231-6ef8c400-8bc0-11ea-815d-1c1970113bc1.png)
